# This file is generated by ../helper/update-flake.nix
pkgs: pkgsUnstable:
{
  inherit (pkgs)
    bitcoind-knots
    charge-lnd
    clboss
    elementsd
    extra-container
    fulcrum
    hwi
    lightning-pool
    lndconnect;

  inherit (pkgsUnstable)
    bitcoin
    bitcoind
    bitcoin-knots
    btcpayserver
    clightning
    electrs
    lightning-loop
    lnd;

  # Version pin for datum-gateway
  datum-gateway = {
    version = "0.3.1beta";
    owner = "OCEAN-xyz";
    repo = "datum_gateway";
    rev = "v0.3.1beta";
    sha256 = "sha256-0soLkz5YFe9ZQKzhp86zIqs7oemBliDvYCg/uLUKMwA=";
  };

  inherit pkgs pkgsUnstable;
}
