# This file is generated by ../helper/update-flake.nix
pkgs: pkgsUnstable:
{
  inherit (pkgs)
    bitcoind-knots
    charge-lnd
    clboss
    elementsd
    extra-container
    fulcrum
    hwi
    lightning-pool
    lndconnect;

  inherit (pkgsUnstable)
    bitcoin
    bitcoind
    bitcoin-knots
    btcpayserver
    clightning
    electrs
    lightning-loop
    lnd;

  # Version pin for datum-gateway (source attributes, not the package)
  # Named with -src suffix to avoid collision with the actual package in default.nix
  datum-gateway-src = {
    version = "0.4.1beta";
    owner = "OCEAN-xyz";
    repo = "datum_gateway";
    rev = "v0.4.1beta";
    sha256 = "sha256-EKU+c22t/vc9FC4wg7+p3C+dJO61ZIGsEn9c1q1TBFQ=";
  };

  inherit pkgs pkgsUnstable;
}
